services:
  core:
    image: notiziario:latest
    env_file:
      - .env
    depends_on:
      - db
  
  
  db:
    image: qdrant/qdrant:latest
    volumes:
      - ./qdrant_data:/qdrant/storage/
    ports:
      - "6333:6333"
      - "6334:6334"
    
    

