services:
  core:
    image: notiziario:latest
    env_file:
      - .env
    depends_on:
      - db
  
  
  db:
    image: qdrant/qdrant:latest
    volumes:
      - ./qdrant_data:/qdrant/storage/
    ports:
      - "6333:6333"
      - "6334:6334"
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: notiziario

    

